### ISSUE TITLE
Font too big for German language (text cut off in lockscreen)

### ISSUE THREAD

**Issue by Va-ki** [Kalyvara/NXTheme-CHROMA#3]
Great theme, however since the font is this big size it causes the text for "press 3 times" on the lockscreen to be 50% cut off in German language. Any way to fix this or maybe reduce font size?

**Comment by Kalyvara** [comment]
That's a language dependent fix I'm afraid, my themes are indeed optimized for US English. There's no notion of responsive design in Switch theming (like the ability for content to adapt or re-adjust), all elements are absolutely positioned, which explains the cut off.

Fixing this is just a matter of offsetting one particular X coordinate in the JSON layout though. I can give you directions if you're willing to make this quick edit yourself. If not I'd recommend to pick an alternative lockscreen layout.

**Comment by Va-ki** [comment]
ah thats a shame, thanks for the help tho!

i will just switch the language to English on my switch it looks cleaner anyway
